spring.application.name=ProjectoIntegradorSpring
spring.datasource.url=jdbc:h2mem:superdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=admin
spring.datasource.password=
# PARA QUE H2 SE COMPORTE COMO MySQL (importante para test)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console